// <auto-generated />
using System;
using AppApi.DataAccess.Base;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace AppApi.DataAccess.Migrations.WebApi
{
    [DbContext(typeof(WebApiDbContext))]
    partial class WebApiDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.17")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.Property<Guid>("AccountsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("RolesId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("AccountsId", "RolesId");

                    b.HasIndex("RolesId");

                    b.ToTable("AccountRole");
                });

            modelBuilder.Entity("ApiRoleMappingMenuItem", b =>
                {
                    b.Property<Guid>("ApiRoleMappingsId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("MenuItemsId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("ApiRoleMappingsId", "MenuItemsId");

                    b.HasIndex("MenuItemsId");

                    b.ToTable("ApiRoleMappingMenuItem");
                });

            modelBuilder.Entity("AppApi.Entities.Models.Account", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<long?>("DonViId")
                        .HasColumnType("bigint");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("FullName")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsLock")
                        .HasColumnType("bit");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Pseudonym")
                        .HasColumnType("NVARCHAR(1000)");

                    b.Property<string>("Salt")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("TimeLock")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("VerifacationCode")
                        .HasColumnType("NVARCHAR(10)");

                    b.HasKey("Id");

                    b.HasIndex("Username")
                        .IsUnique();

                    b.ToTable("Account");
                });

            modelBuilder.Entity("AppApi.Entities.Models.AccountGroupRole", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("AccountId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.HasKey("Id");

                    b.HasIndex("GroupId");

                    b.ToTable("AccountGroupRole");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ApiRoleMapping", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Action")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("AllowedRoles")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Controller")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("ApiRoleMapping");
                });

            modelBuilder.Entity("AppApi.Entities.Models.BuocQuyTrinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("BatBuoc")
                        .HasColumnType("bit");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiForm")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("MaBuoc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("NhomQuyTrinh")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("RoleXuLyChinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("TenBuoc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<int>("ThuTu")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("BuocQuyTrinh");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DanhGiaNhaThau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiemTong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("NhaThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NhanXet")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime?>("ThoiDiemDanhGia")
                        .HasColumnType("datetime2");

                    b.Property<string>("TieuChiJson")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("XepLoai")
                        .HasColumnType("NVARCHAR(50)");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NhaThauId");

                    b.ToTable("DanhGiaNhaThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DeXuatChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeXuatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("DonGiaUocTinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHang")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenHangHoaDichVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeXuatId");

                    b.ToTable("DeXuatChiTiet");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DeXuatMuaSam", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonViDeXuatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LyDo")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("MaDeXuat")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("MoTaChung")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<int>("NamKeHoach")
                        .HasColumnType("int");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenDeXuat")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<decimal>("TongGiaTriUocTinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TrangThai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonViDeXuatId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("DeXuatMuaSam");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DonVi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViChaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiDonVi")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("MaDonVi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("TenDonVi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<int?>("ThuTu")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonViChaId");

                    b.ToTable("DonVi");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DuToanChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CanCu")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("DonGiaDuToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("DuToanGoiThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenHangHoaDichVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DuToanGoiThauId");

                    b.ToTable("DuToanChiTiet");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DuToanGoiThau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("GhiChu")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<decimal>("GiaTriSauThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal>("GiaTriTruocThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime>("NgayLap")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiLapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("TienThue")
                        .HasColumnType("decimal(18,2)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NguoiLapId");

                    b.ToTable("DuToanGoiThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.EmailConfig", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("EmailTitle")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("EnableSSl")
                        .HasColumnType("bit");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MailServer")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("Password")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<int>("Port")
                        .HasColumnType("int");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("EmailConfig");
                });

            modelBuilder.Entity("AppApi.Entities.Models.FileDinhKem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DuongDan")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<Guid?>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiFile")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime>("NgayUpload")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiUploadId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenFileGoc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("TenHienThi")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<Guid?>("TienTrinhHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NguoiUploadId");

                    b.HasIndex("TienTrinhHoSoId");

                    b.ToTable("FileDinhKem");
                });

            modelBuilder.Entity("AppApi.Entities.Models.FileManager", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("FilePath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<int>("FileSizeInKB")
                        .HasColumnType("int");

                    b.Property<string>("FileType")
                        .HasColumnType("NVARCHAR(10)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("PhysicalPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("PhysicalThumbPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("ThumbPath")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("FileManager");
                });

            modelBuilder.Entity("AppApi.Entities.Models.GoiThauDeXuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DeXuatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("GoiThauKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DeXuatId");

                    b.HasIndex("GoiThauKeHoachId");

                    b.ToTable("GoiThauDeXuat");
                });

            modelBuilder.Entity("AppApi.Entities.Models.GoiThauKeHoach", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonViDeXuatChinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViMuaSamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaTriDuKien")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("HinhThucLCNTDuKien")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinhVuc")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LoaiMuaSam")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LoaiQuyTrinhDuKien")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("MaGoi")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("NamKeHoach")
                        .HasColumnType("int");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("TenGoiThau")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThaiKeHoach")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonViDeXuatChinhId");

                    b.HasIndex("DonViMuaSamId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("GoiThauKeHoach");
                });

            modelBuilder.Entity("AppApi.Entities.Models.Group", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(150)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Group");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HoSoDuThau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DiemKyThuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiemTaiChinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaDeXuat")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaDuThau")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("GiaSauDieuChinh")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetLuan")
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<Guid>("NhaThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int?>("XepHang")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NhaThauId");

                    b.ToTable("HoSoDuThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HoSoThau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuocHienTai")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DonViDeXuatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("DonViMuaSamId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<decimal>("GiaTriDuToan")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid?>("GoiThauKeHoachId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("HinhThucLCNT")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LinhVuc")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LoaiMuaSam")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LoaiQuyTrinh")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<int>("Nam")
                        .HasColumnType("int");

                    b.Property<Guid?>("NguoiTaoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NguonVon")
                        .HasColumnType("NVARCHAR(200)");

                    b.Property<string>("SoHoSo")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("TenGoiThau")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<DateTime?>("ThoiGianDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTu")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThaiTong")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("DonViDeXuatId");

                    b.HasIndex("DonViMuaSamId");

                    b.HasIndex("GoiThauKeHoachId");

                    b.HasIndex("NguoiTaoId");

                    b.ToTable("HoSoThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HopDong", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BaoHanhThongTin")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("GiaTriHopDong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayKy")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("NhaThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("SoHopDong")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("ThoiGianDen")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ThoiGianTu")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(30)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NhaThauId");

                    b.ToTable("HopDong");
                });

            modelBuilder.Entity("AppApi.Entities.Models.Log", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedDate")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Message")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Parameter")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.HasKey("Id");

                    b.ToTable("Log");
                });

            modelBuilder.Entity("AppApi.Entities.Models.LoginHistory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AccountId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("LoginDate")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UserName")
                        .HasColumnType("NVARCHAR(250)");

                    b.HasKey("Id");

                    b.HasIndex("AccountId");

                    b.ToTable("LoginHistory");
                });

            modelBuilder.Entity("AppApi.Entities.Models.MenuItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Icon")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("Path")
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("Title")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("MenuItem");
                });

            modelBuilder.Entity("AppApi.Entities.Models.NghiemThu", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FileBienBanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HopDongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetQua")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<DateTime?>("NgayNghiemThu")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDung")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileBienBanId");

                    b.HasIndex("HopDongId");

                    b.ToTable("NghiemThu");
                });

            modelBuilder.Entity("AppApi.Entities.Models.NhaThau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DiaChi")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("DienThoai")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("Email")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LienHe")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("MaSoThue")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("TenNhaThau")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("NhaThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.Role", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<int>("OrderNumber")
                        .HasColumnType("int");

                    b.Property<Guid?>("ParentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("Role");
                });

            modelBuilder.Entity("AppApi.Entities.Models.Test", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("TestCode")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<string>("TestName")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("Test");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThamDinh", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("KetLuan")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("KienNghi")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("LoaiThamDinh")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime>("NgayThamDinh")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiThamDinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<Guid?>("TienTrinhHoSoId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NguoiThamDinhId");

                    b.HasIndex("TienTrinhHoSoId");

                    b.ToTable("ThamDinh");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThanhToan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<int>("DotThanhToan")
                        .HasColumnType("int");

                    b.Property<string>("GhiChu")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<decimal>("GiaTri")
                        .HasColumnType("decimal(18,2)");

                    b.Property<Guid>("HopDongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayThanhToan")
                        .HasColumnType("datetime2");

                    b.Property<string>("TaiLieuChungTu")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HopDongId");

                    b.ToTable("ThanhToan");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThanhVienToChuyenGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonVi")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<string>("HoTen")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<Guid>("ToChuyenGiaId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("VaiTro")
                        .HasColumnType("NVARCHAR(100)");

                    b.HasKey("Id");

                    b.HasIndex("ToChuyenGiaId");

                    b.ToTable("ThanhVienToChuyenGia");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThongTinKyThuat", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MoTaChung")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<DateTime>("NgayNhap")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiNhapId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NguoiNhapId");

                    b.ToTable("ThongTinKyThuat");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThongTinKyThuatChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DonViTinh")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("GhiChu")
                        .HasColumnType("NVARCHAR(500)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("MaHang")
                        .HasColumnType("NVARCHAR(100)");

                    b.Property<decimal>("SoLuong")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TenHangHoaDichVu")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<Guid>("ThongTinKyThuatId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YeuCauKyThuat")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("ThongTinKyThuatId");

                    b.ToTable("ThongTinKyThuatChiTiet");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiBaoGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HanNhan")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTomTat")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.ToTable("ThuMoiBaoGia");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiBaoGiaChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhThucGui")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("NhaThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThongTinLienHe")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<Guid>("ThuMoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhaThauId");

                    b.HasIndex("ThuMoiId");

                    b.ToTable("ThuMoiBaoGia_ChiTiet");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiThau", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("HanNhan")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("Loai")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<DateTime?>("NgayGui")
                        .HasColumnType("datetime2");

                    b.Property<string>("NoiDungTomTat")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("HoSoThauId");

                    b.ToTable("ThuMoiThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiThauChiTiet", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("HinhThucGui")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<Guid>("NhaThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("ThongTinLienHe")
                        .HasColumnType("NVARCHAR(255)");

                    b.Property<Guid>("ThuMoiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NhaThauId");

                    b.HasIndex("ThuMoiId");

                    b.ToTable("ThuMoiThau_ChiTiet");
                });

            modelBuilder.Entity("AppApi.Entities.Models.TienTrinhHoSo", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("BuocQuyTrinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("DonViXuLyThucTeId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("GhiChu")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("NgayBatDau")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("NgayKetThuc")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("NguoiXuLyId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThaiBuoc")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("YKien")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.HasKey("Id");

                    b.HasIndex("BuocQuyTrinhId");

                    b.HasIndex("DonViXuLyThucTeId");

                    b.HasIndex("HoSoThauId");

                    b.HasIndex("NguoiXuLyId");

                    b.ToTable("TienTrinhHoSo");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ToChuyenGia", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid?>("FileQuyetDinhId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("HoSoThauId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiTo")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime?>("NgayQuyetDinh")
                        .HasColumnType("datetime2");

                    b.Property<string>("SoQuyetDinh")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("FileQuyetDinhId");

                    b.HasIndex("HoSoThauId");

                    b.ToTable("ToChuyenGia");
                });

            modelBuilder.Entity("AppApi.Entities.Models.TraoDoi", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("BuocMa")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<string>("CreatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("DoiTuongId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("bit");

                    b.Property<bool>("IsSystem")
                        .HasColumnType("bit");

                    b.Property<string>("LoaiDoiTuong")
                        .IsRequired()
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<Guid>("NguoiGuiId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid?>("NguoiNhanId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("NoiDung")
                        .HasColumnType("NVARCHAR(MAX)");

                    b.Property<string>("RoleNguoiNhan")
                        .HasColumnType("NVARCHAR(50)");

                    b.Property<DateTime>("ThoiGianGui")
                        .HasColumnType("datetime2");

                    b.Property<byte[]>("Timestamp")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("rowversion");

                    b.Property<string>("TrangThai")
                        .HasColumnType("NVARCHAR(20)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("NVARCHAR(250)");

                    b.Property<DateTime?>("UpdatedDate")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.HasIndex("NguoiGuiId");

                    b.HasIndex("NguoiNhanId");

                    b.ToTable("TraoDoi");
                });

            modelBuilder.Entity("AccountRole", b =>
                {
                    b.HasOne("AppApi.Entities.Models.Account", null)
                        .WithMany()
                        .HasForeignKey("AccountsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Role", null)
                        .WithMany()
                        .HasForeignKey("RolesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("ApiRoleMappingMenuItem", b =>
                {
                    b.HasOne("AppApi.Entities.Models.ApiRoleMapping", null)
                        .WithMany()
                        .HasForeignKey("ApiRoleMappingsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.MenuItem", null)
                        .WithMany()
                        .HasForeignKey("MenuItemsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("AppApi.Entities.Models.AccountGroupRole", b =>
                {
                    b.HasOne("AppApi.Entities.Models.Group", "Group")
                        .WithMany("AccountGroupRoles")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Group");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DanhGiaNhaThau", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany("DanhGiaNhaThaus")
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.NhaThau", "NhaThau")
                        .WithMany("DanhGiaNhaThaus")
                        .HasForeignKey("NhaThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoThau");

                    b.Navigation("NhaThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DeXuatChiTiet", b =>
                {
                    b.HasOne("AppApi.Entities.Models.DeXuatMuaSam", "DeXuat")
                        .WithMany("DeXuatChiTiets")
                        .HasForeignKey("DeXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeXuat");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DeXuatMuaSam", b =>
                {
                    b.HasOne("AppApi.Entities.Models.DonVi", "DonViDeXuat")
                        .WithMany("DeXuatMuaSams")
                        .HasForeignKey("DonViDeXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId");

                    b.Navigation("DonViDeXuat");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DonVi", b =>
                {
                    b.HasOne("AppApi.Entities.Models.DonVi", "DonViCha")
                        .WithMany("DonViCon")
                        .HasForeignKey("DonViChaId")
                        .OnDelete(DeleteBehavior.NoAction);

                    b.Navigation("DonViCha");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DuToanChiTiet", b =>
                {
                    b.HasOne("AppApi.Entities.Models.DuToanGoiThau", "DuToanGoiThau")
                        .WithMany("DuToanChiTiets")
                        .HasForeignKey("DuToanGoiThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DuToanGoiThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DuToanGoiThau", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany()
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiLap")
                        .WithMany()
                        .HasForeignKey("NguoiLapId");

                    b.Navigation("HoSoThau");

                    b.Navigation("NguoiLap");
                });

            modelBuilder.Entity("AppApi.Entities.Models.FileDinhKem", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany("FileDinhKems")
                        .HasForeignKey("HoSoThauId");

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiUpload")
                        .WithMany()
                        .HasForeignKey("NguoiUploadId");

                    b.HasOne("AppApi.Entities.Models.TienTrinhHoSo", "TienTrinhHoSo")
                        .WithMany("FileDinhKems")
                        .HasForeignKey("TienTrinhHoSoId");

                    b.Navigation("HoSoThau");

                    b.Navigation("NguoiUpload");

                    b.Navigation("TienTrinhHoSo");
                });

            modelBuilder.Entity("AppApi.Entities.Models.GoiThauDeXuat", b =>
                {
                    b.HasOne("AppApi.Entities.Models.DeXuatMuaSam", "DeXuat")
                        .WithMany("GoiThauDeXuats")
                        .HasForeignKey("DeXuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.GoiThauKeHoach", "GoiThauKeHoach")
                        .WithMany("GoiThauDeXuats")
                        .HasForeignKey("GoiThauKeHoachId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeXuat");

                    b.Navigation("GoiThauKeHoach");
                });

            modelBuilder.Entity("AppApi.Entities.Models.GoiThauKeHoach", b =>
                {
                    b.HasOne("AppApi.Entities.Models.DonVi", "DonViDeXuatChinh")
                        .WithMany("GoiThauKeHoach_DeXuatChinh")
                        .HasForeignKey("DonViDeXuatChinhId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.DonVi", "DonViMuaSam")
                        .WithMany("GoiThauKeHoach_MuaSam")
                        .HasForeignKey("DonViMuaSamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId");

                    b.Navigation("DonViDeXuatChinh");

                    b.Navigation("DonViMuaSam");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HoSoDuThau", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany()
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.NhaThau", "NhaThau")
                        .WithMany()
                        .HasForeignKey("NhaThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoThau");

                    b.Navigation("NhaThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HoSoThau", b =>
                {
                    b.HasOne("AppApi.Entities.Models.DonVi", "DonViDeXuat")
                        .WithMany()
                        .HasForeignKey("DonViDeXuatId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.DonVi", "DonViMuaSam")
                        .WithMany()
                        .HasForeignKey("DonViMuaSamId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.GoiThauKeHoach", "GoiThauKeHoach")
                        .WithMany()
                        .HasForeignKey("GoiThauKeHoachId");

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiTao")
                        .WithMany()
                        .HasForeignKey("NguoiTaoId");

                    b.Navigation("DonViDeXuat");

                    b.Navigation("DonViMuaSam");

                    b.Navigation("GoiThauKeHoach");

                    b.Navigation("NguoiTao");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HopDong", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany()
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.NhaThau", "NhaThau")
                        .WithMany()
                        .HasForeignKey("NhaThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoThau");

                    b.Navigation("NhaThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.LoginHistory", b =>
                {
                    b.HasOne("AppApi.Entities.Models.Account", "Account")
                        .WithMany("LoginHistory")
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("AppApi.Entities.Models.MenuItem", b =>
                {
                    b.HasOne("AppApi.Entities.Models.MenuItem", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId");

                    b.Navigation("Parent");
                });

            modelBuilder.Entity("AppApi.Entities.Models.NghiemThu", b =>
                {
                    b.HasOne("AppApi.Entities.Models.FileDinhKem", "FileBienBan")
                        .WithMany()
                        .HasForeignKey("FileBienBanId");

                    b.HasOne("AppApi.Entities.Models.HopDong", "HopDong")
                        .WithMany("NghiemThus")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileBienBan");

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThamDinh", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany()
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiThamDinh")
                        .WithMany()
                        .HasForeignKey("NguoiThamDinhId");

                    b.HasOne("AppApi.Entities.Models.TienTrinhHoSo", "TienTrinhHoSo")
                        .WithMany()
                        .HasForeignKey("TienTrinhHoSoId");

                    b.Navigation("HoSoThau");

                    b.Navigation("NguoiThamDinh");

                    b.Navigation("TienTrinhHoSo");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThanhToan", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HopDong", "HopDong")
                        .WithMany("ThanhToans")
                        .HasForeignKey("HopDongId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HopDong");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThanhVienToChuyenGia", b =>
                {
                    b.HasOne("AppApi.Entities.Models.ToChuyenGia", "ToChuyenGia")
                        .WithMany()
                        .HasForeignKey("ToChuyenGiaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ToChuyenGia");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThongTinKyThuat", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany("ThongTinKyThuats")
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiNhap")
                        .WithMany()
                        .HasForeignKey("NguoiNhapId");

                    b.Navigation("HoSoThau");

                    b.Navigation("NguoiNhap");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThongTinKyThuatChiTiet", b =>
                {
                    b.HasOne("AppApi.Entities.Models.ThongTinKyThuat", "ThongTinKyThuat")
                        .WithMany()
                        .HasForeignKey("ThongTinKyThuatId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ThongTinKyThuat");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiBaoGia", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany()
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiBaoGiaChiTiet", b =>
                {
                    b.HasOne("AppApi.Entities.Models.NhaThau", "NhaThau")
                        .WithMany()
                        .HasForeignKey("NhaThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.ThuMoiBaoGia", "ThuMoiBaoGia")
                        .WithMany()
                        .HasForeignKey("ThuMoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaThau");

                    b.Navigation("ThuMoiBaoGia");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiThau", b =>
                {
                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany()
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("HoSoThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ThuMoiThauChiTiet", b =>
                {
                    b.HasOne("AppApi.Entities.Models.NhaThau", "NhaThau")
                        .WithMany()
                        .HasForeignKey("NhaThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.ThuMoiThau", "ThuMoiThau")
                        .WithMany()
                        .HasForeignKey("ThuMoiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("NhaThau");

                    b.Navigation("ThuMoiThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.TienTrinhHoSo", b =>
                {
                    b.HasOne("AppApi.Entities.Models.BuocQuyTrinh", "BuocQuyTrinh")
                        .WithMany("TienTrinhHoSos")
                        .HasForeignKey("BuocQuyTrinhId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.DonVi", "DonViXuLyThucTe")
                        .WithMany()
                        .HasForeignKey("DonViXuLyThucTeId");

                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany("TienTrinhHoSos")
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiXuLy")
                        .WithMany()
                        .HasForeignKey("NguoiXuLyId");

                    b.Navigation("BuocQuyTrinh");

                    b.Navigation("DonViXuLyThucTe");

                    b.Navigation("HoSoThau");

                    b.Navigation("NguoiXuLy");
                });

            modelBuilder.Entity("AppApi.Entities.Models.ToChuyenGia", b =>
                {
                    b.HasOne("AppApi.Entities.Models.FileDinhKem", "FileQuyetDinh")
                        .WithMany()
                        .HasForeignKey("FileQuyetDinhId");

                    b.HasOne("AppApi.Entities.Models.HoSoThau", "HoSoThau")
                        .WithMany()
                        .HasForeignKey("HoSoThauId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("FileQuyetDinh");

                    b.Navigation("HoSoThau");
                });

            modelBuilder.Entity("AppApi.Entities.Models.TraoDoi", b =>
                {
                    b.HasOne("AppApi.Entities.Models.Account", "NguoiGui")
                        .WithMany()
                        .HasForeignKey("NguoiGuiId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("AppApi.Entities.Models.Account", "NguoiNhan")
                        .WithMany()
                        .HasForeignKey("NguoiNhanId");

                    b.Navigation("NguoiGui");

                    b.Navigation("NguoiNhan");
                });

            modelBuilder.Entity("AppApi.Entities.Models.Account", b =>
                {
                    b.Navigation("LoginHistory");
                });

            modelBuilder.Entity("AppApi.Entities.Models.BuocQuyTrinh", b =>
                {
                    b.Navigation("TienTrinhHoSos");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DeXuatMuaSam", b =>
                {
                    b.Navigation("DeXuatChiTiets");

                    b.Navigation("GoiThauDeXuats");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DonVi", b =>
                {
                    b.Navigation("DeXuatMuaSams");

                    b.Navigation("DonViCon");

                    b.Navigation("GoiThauKeHoach_DeXuatChinh");

                    b.Navigation("GoiThauKeHoach_MuaSam");
                });

            modelBuilder.Entity("AppApi.Entities.Models.DuToanGoiThau", b =>
                {
                    b.Navigation("DuToanChiTiets");
                });

            modelBuilder.Entity("AppApi.Entities.Models.GoiThauKeHoach", b =>
                {
                    b.Navigation("GoiThauDeXuats");
                });

            modelBuilder.Entity("AppApi.Entities.Models.Group", b =>
                {
                    b.Navigation("AccountGroupRoles");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HoSoThau", b =>
                {
                    b.Navigation("DanhGiaNhaThaus");

                    b.Navigation("FileDinhKems");

                    b.Navigation("ThongTinKyThuats");

                    b.Navigation("TienTrinhHoSos");
                });

            modelBuilder.Entity("AppApi.Entities.Models.HopDong", b =>
                {
                    b.Navigation("NghiemThus");

                    b.Navigation("ThanhToans");
                });

            modelBuilder.Entity("AppApi.Entities.Models.MenuItem", b =>
                {
                    b.Navigation("Children");
                });

            modelBuilder.Entity("AppApi.Entities.Models.NhaThau", b =>
                {
                    b.Navigation("DanhGiaNhaThaus");
                });

            modelBuilder.Entity("AppApi.Entities.Models.TienTrinhHoSo", b =>
                {
                    b.Navigation("FileDinhKems");
                });
#pragma warning restore 612, 618
        }
    }
}
